version: 2
jobs:
  deploy-backend:
    docker:
      - image: rastasheep/ubuntu-sshd
    working_directory: ~/repo
    steps:
      - add_ssh_keys:
          fingerprints:
            - "44:ec:8d:af:98:49:d4:27:59:41:ae:f5:9b:8b:87:a5"
      - checkout
      - run:
          name: Add known host
          command: ssh-keyscan -H $SSH_HOST > ~/.ssh/known_hosts
      - run:
          name: SSH deploy
          command: |
            ssh $SSH_USER@$SSH_HOST << EOF
            cd ./reviewhub
            git fetch --all
            git reset --hard origin/$CIRCLE_BRANCH
            docker-compose down
            docker-compose up --build -d
            exit

workflows:
  version: 2
  backend-deploy-flow:
    jobs:
      - deploy-backend:
          filters:
            branches:
              only:
                - master
          context: ddforce-reviewhub
